"""unique partial index on raw_signals.url

Revision ID: 050c18b44914
Revises: 70345c3ebb63
Create Date: 2026-05-12 19:38:02.575284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050c18b44914'
down_revision: Union[str, Sequence[str], None] = '70345c3ebb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_raw_signals_url', 'raw_signals', ['url'], unique=True, postgresql_where=sa.text('url IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_raw_signals_url', table_name='raw_signals', postgresql_where=sa.text('url IS NOT NULL'))
    # ### end Alembic commands ###
