"""add briefs and brief_themes

Revision ID: 0afad88ec17d
Revises: 050c18b44914
Create Date: 2026-05-12 19:53:02.287751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0afad88ec17d'
down_revision: Union[str, Sequence[str], None] = '050c18b44914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brief_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('input_signal_count', sa.Integer(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_briefs_brief_date', 'briefs', [sa.literal_column('brief_date DESC')], unique=False)
    op.create_table('brief_themes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('conviction_score', sa.SmallInteger(), nullable=True),
    sa.Column('source_signal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brief_themes_brief_order', 'brief_themes', ['brief_id', 'display_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brief_themes_brief_order', table_name='brief_themes')
    op.drop_table('brief_themes')
    op.drop_index('ix_briefs_brief_date', table_name='briefs')
    op.drop_table('briefs')
    # ### end Alembic commands ###
