"""add source_types jsonb column to brief_themes

Revision ID: 35ad2e474df6
Revises: 96b2a227514b
Create Date: 2026-05-13 00:07:49.810876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35ad2e474df6'
down_revision: Union[str, Sequence[str], None] = '96b2a227514b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brief_themes', sa.Column('source_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brief_themes', 'source_types')
    # ### end Alembic commands ###
