"""add categories jsonb column to brief_themes

Revision ID: 96b2a227514b
Revises: e10bfa2e7d11
Create Date: 2026-05-12 23:07:26.530332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96b2a227514b'
down_revision: Union[str, Sequence[str], None] = 'e10bfa2e7d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brief_themes', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brief_themes', 'categories')
    # ### end Alembic commands ###
