"""add primary_signal_id to brief_themes

Revision ID: e10bfa2e7d11
Revises: 0afad88ec17d
Create Date: 2026-05-12 21:12:54.106523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10bfa2e7d11'
down_revision: Union[str, Sequence[str], None] = '0afad88ec17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brief_themes', sa.Column('primary_signal_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'brief_themes', 'raw_signals', ['primary_signal_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brief_themes', type_='foreignkey')
    op.drop_column('brief_themes', 'primary_signal_id')
    # ### end Alembic commands ###
